title: angular-reset-on
description: Resets a field to its initial value (or cleans) when given scope expression is true.
google_analytics: 
show_downloads: true
theme: jekyll-theme-tactile

gems:
  - jekyll-mentions
